
@host = http://localhost:8080/matchboxv3/fhir


### Compile MetaToSourceSystem.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/MetaSourceToSourceSystem.map


### Compile BundleToLoopSphn.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/BundleToLoopSphn.map


### Compile EncounterToAdministrativeCase.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/EncounterToAdministrativeCase.map


### Compile ObservationVitalSignToMeasurement.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/ObservationVitalSignToMeasurement.map


### Compile AllergyIntoleranceToAllergy.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/AllergyIntoleranceToAllergy.map


### Compile ConditionToProblemCondition.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/ConditionToProblemCondition.map


### Compile DiagnosticReportToLabTestEvent.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/DiagnosticReportToLabTestEvent.map


### transform sample input
POST {{host}}/StructureMap/$transform?source=http://research.balgrist.ch/fhir2sphn/StructureMap/BundleToLoopSphn
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./testdata/pat.json


### Optional: Update individual SD (already loaded with IG)
POST {{host}}/StructureDefinition HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources//StructureDefinition-LoopSphn.json


### Optional: Check installed IGs
GET {{host}}/ImplementationGuide HTTP/1.1
Accept: application/fhir+json


### Optional: Validate
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Bundle
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./testdata/pat.json
