
@host = http://localhost:8080/matchboxv3/fhir

### 1. Compile BundleToLoopSphn.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/BundleToLoopSphn.map


### 2. Compile EncounterToAdministrativeCase.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/EncounterToAdministrativeCase.map


### 3. Compile ObservationVitalSignToMeasurement.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/ObservationVitalSignToMeasurement.map


### 4. Compile DiagnosticReportToLabTestEvent.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/DiagnosticReportToLabTestEvent.map

### 5. transform sample input
POST {{host}}/StructureMap/$transform?source=http://research.balgrist.ch/fhir2sphn/StructureMap/BundleToLoopSphn
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./testdata/pat.json


### Optional update individual SD (already loaded with IG)
POST {{host}}/StructureDefinition HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources//StructureDefinition-LoopSphn.json


### Check installed IGs
GET {{host}}/ImplementationGuide HTTP/1.1
Accept: application/fhir+json
